### PR TITLE
update Moderations categories; obsolete endpoint /v1/edits; type safe model for Queries, Strings for model Results, require "edits" field for ImageEditsQuery

### PR DESCRIPTION
**Pull request by kalafus**
Thanks for allowing me to contribute to MacPaw/OpenAI 😊

## What

Adds support for new Moderations categories.

## Why

There are four (4) unsupported Moderations categories for: harassment, harassment/threatening, self-harm/intent, & self-harm/instructions.

## Affected Areas

"Moderations" API affected.

### CODE REVIEW

**Comment by kalafus** [comment]
## What

/v1/edits endpoint removed

## Why

/v1/edits endpoint invalid

curl https://api.openai.com/v1/edits \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "gpt-3.5-turbo-1106",
    "input": "fudeg",
    "instruction": "correct spelling"
  }'

{
  "error": {
    "message": "Invalid URL (POST /v1/edits)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

## Affected Areas

endpoints

**Comment by kalafus** [comment]
## What

type safe models
fix for ImageEditsQuery: require "edits" field 

## Why

most models lacked validation. cleaner, more maintainable, and less error prone to convert to Query specific typesafe enums (and remove limited existing validation) than to implement validation across the board.

ImageEditsQuery endpoint "/v1/images/edits" was not working. error message said something about requiring RGBA, or grayscale. And yet RGBA submissions were rejected too. Then i tried submitting with an alpha mask in the "edits" field, and the endpoint worked. So the "edits" field is required.

## Affected Areas

Model, Query, Result

**Comment by kalafus** [comment]
Subscription to ChatGPTPlus required for GPT 4 and Dall-E 3; these models are present but commented out, as are the GPT 3 models that have been superseded and are scheduled to be deprecated June 13, 2024.

**Comment by SunburstEnzo** [comment]
Between the linting and the amount of other changes I'm struggling to understand what's an intentional change or not – could you break up the PR into smaller PRs please? It's great to see linting being done but there should likely be a cleanup PR dedicated just for that to make sure nothing sneaks in accidentally.

**Comment by kalafus** [comment]
sorry, first pull request; will submit clean, partitioned code changes.

**Pull request closed without merging**
