### PR TITLE
Fix: prevent json decoding error when streaming

### PR DESCRIPTION
**Pull request by neelvirdy**
## What

Filter empty json content after trimming whitespace instead of before

## Why

Addresses https://github.com/MacPaw/OpenAI/issues/128 and https://github.com/MacPaw/OpenAI/issues/153

## Affected Areas

--

Fix inspired by this comment https://github.com/MacPaw/OpenAI/pull/151#issuecomment-1913703132

### CODE REVIEW

**Review by ruben-storyarc-studios — APPROVED** [review]
Thanks! for doing this This fixes it on my app as well

**Review by manurueda — APPROVED** [review]

**Review by manurueda — APPROVED** [review]
Ready to go

**Review by ingvarus-bc — APPROVED** [review]

**Comment by ingvarus-bc** [comment]
Thanks for the fix! 🔥

**Comment by csmac3144** [comment]
Same issue -- when can we expect an update to the package?

**Comment by manurueda** [comment]
already merged @csmac3144

**Pull request merged**
