### PR TITLE
Fix the issue where it does not decode the Error correctly when streaming response

### PR DESCRIPTION
**Pull request by longseespace**
## What

When using streaming, there might be an error occurring in the middle of the streaming.

This PR fixes it.

Previous PR: https://github.com/MacPaw/OpenAI/pull/87

## Why

Related: https://github.com/MacPaw/OpenAI/issues/88

## Affected Areas

`StreamingSession.swift`

### CODE REVIEW

**Review by gavtron2000 — APPROVED** [review]

**Comment by longseespace** [comment]
Hey @Krivoblotsky, can you merge this?

**Comment by Krivoblotsky** [comment]
Yup, will add it to the release scope 👌

**Comment by longseespace** [comment]
@Krivoblotsky  Also do you think we should switch to a new implementation. I find the current one quite problematic.

For example, this issue: https://github.com/MacPaw/OpenAI/issues/97

Another issue I encountered is when working with OpenAI-compatible services, they might use SSE comments (started with `:`). It won't work with the current implementation.

**Comment by Krivoblotsky** [comment]
@longseespace let's do it with separate PR to reduce changes size plz 🙏

**Pull request merged**
