### PR TITLE
add scheme, host, and port for buildURL

### PR DESCRIPTION
**Pull request by JavadFaghih**
## What

add scheme, host, and port for buildURL

## Why

for comuincate with local backend server

## Affected Areas

building url for request

### CODE REVIEW

**Comment by tisfeng** [comment]
Can anyone take a look at this PR?

**Comment by thekoc** [comment]
It's such a quality of life improvement and has been mentioned multiple times:

https://github.com/MacPaw/OpenAI/issues/179
https://github.com/MacPaw/OpenAI/issues/68
https://github.com/MacPaw/OpenAI/issues/74
https://github.com/MacPaw/OpenAI/issues/61

Not to mention it is supported by the official open python library:
```
# all client options can be configured just like the `OpenAI` instantiation counterpart
openai.base_url = "https://..."
openai.default_headers = {"x-foo": "true"}
```

Could any one check it out?

 @ingvarus-bc

**Comment by Krivoblotsky** [comment]
Thanks, 
We will include this change in the next release.

**Review by ingvarus-bc — APPROVED** [review]

**Comment by ingvarus-bc** [comment]
Hey! 👋
Thanks a lot for your contribution! 🔥

**Pull request merged**
