### PR TITLE
Add custom request url

### PR DESCRIPTION
**Pull request by iHTCboy**
Customization api url #27

### CODE REVIEW

**Comment by Krivoblotsky** [comment]
Hey, @iHTCboy.
Thanks for the pull request.
Please update `OpenAI+Extensions.swift` as well, so async/await functions also reflect the change.

**Comment by iHTCboy** [comment]
@Krivoblotsky Thank you for your reminder, I have re-updated the submission now, we hope to merge and update the version immediately, we hope to use the latest code in our project [37iOS/iChatGPT), thank you~

**Comment by Krivoblotsky** [comment]
Implemented by #33

**Comment by Krivoblotsky** [comment]
@iHTCboy, your contribution is very appreciated 👍

**Pull request closed without merging**
