### PR TITLE
Correctly handle partial JSON at the end of a chunk

### PR DESCRIPTION
**Pull request by PallavAg**
## What

Streaming a response occasionally encounters the error `"The given data was not valid JSON."`
Related Issues: #97 #103

## Why

The end of a chunk can have an incomplete JSON. 
The rest of the JSON will come through at the beginning of the next chunk.

## Affected Areas

`StreamingSession.swift`

## More Info
This change stores the last JSON from the chunk and appends it to the beginning of the next chunk.

A likely partial JSON is stored when: 
1. `ResultType` decoding fails
2. `APIErrorResponse` decoding fails
3. The JSON is last in the chunk

---

Having an incomplete JSON at the end of a chunk is seemingly random - likely based on OpenAI server load etc.
A request that surfaces this issue more often than not is: `"Write 1 to 40 using bullet points"`

```json
// Sample incomplete chunk
{"id":"chatcmpl-893wTs9tI87Yt0t6moRbyhXT2xn93","object":"chat.completion.chunk","created":1697170797,"model":"gpt-4-0613","choices":[{"index":0,"delta":{"content":"."},"fi
```

---
Kudos to [@jcmourey](https://github.com/jcmourey) for suggesting the fix in #97

### CODE REVIEW

**Comment by PSchmiedmayer** [comment]
Nice, great addition @PallavAg, we run experience the same issue as noted in #103, this looks like a nice and useful fix, makes sense that it is not guaranteed that each streaming package contains a fully contained JSON.

Would be amazing if this can be merged and added in a next release.

**Comment by ingvarus-bc** [comment]
Neat! 🔥
Amazing addition to the project. What do you think about moving all json handling outside of `urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive data: Data)` to a separate method for the sake of testability and more obvious look?

**Comment by ingvarus-bc** [comment]
@PallavAg, hi, I just moved json processing out, what do you think?

**Review by ingvarus-bc — APPROVED** [review]

**Comment by prateekshac1** [comment]
It looks like this issue has started to happen again. Have noticed the intensity of this go up in the past 2-3 days. I'm using the latest version of OpenAI 0.2.5 which has his fix. But yet many of my chatsStream(query: query) queries are erroring out with this error 

> "The data couldn’t be read because it isn’t in the correct format. dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Unable to parse empty data." UserInfo={NSDebugDescription=Unable to parse empty data.})))"

**Pull request merged**
