### PR TITLE
Size enum for ImagesQuery

### PR DESCRIPTION
**Pull request by kalafus**
## What

Size enum for ImagesQuery

## Why

only certain magic strings are accepted by the endpoint, so use define them with an enum.

## Affected Areas

ImagesQuery > openAI.images(...)

### CODE REVIEW

**Review by kalafus — COMMENTED** [review]
for merge compatibility with MacPaw.views_abstraction.
Ready for merge into main!

**Comment by SunburstEnzo** [comment]
Good idea 👍 tempted to even suggest using `small`, `medium`, and `large` with dimensions in the documentation

**Comment by kalafus** [comment]
i'm more prone to make it more specific with `_256_256` `_512_512` and `_1024_1024`, given that for dall-e-3 it's `_1024_1024`, `_1792_1024`, and `_1024_1792` (commented out). `small`, `medium`, and `large` are fine for User Experience, but i think it's more helpful to the developer writing code to be presented accurate information by Xcode autocomplete.

**Comment by kalafus** [comment]
oh, in the documentation... perhaps. i suppose for dall-e-3, could be `square` `portrait` and `landscape`.

**Comment by kalafus** [comment]
I like the idea... To affect the User Experience, it would require context sensitivity to differentiate Query from View, and I'm not sure how this could be accomplished at all, or especially in a straightforward way.
```    
    /// small: 256x256 pixels (dall-e-2)
    /// medium: 512x512 pixels (dall-e-2)
    /// large: 1024x1024 pixels (dall-e-2, dall-e-3)
    /// large_landscape: 1792x1024 pixels (dall-e-2, dall-e-3)
    /// large_portrait: 1024x1792 pixels (dall-e-2, dall-e-3)
    public enum Size: String, Codable, CaseIterable {
        case small = "256x256" // for dall-e-2 model
        case medium = "512x512" // for dall-e-2 model
        case large = "1024x1024" // for dall-e-2, dall-e-3 models
        case large_landscape = "1792x1024" // for dall-e-3 model
        case large_portrait = "1024x1792" // for dall-e-3 model

    }
```

**Review by ingvarus-bc — APPROVED** [review]

**Pull request merged**
